<template>
  <Container
    class="
      h-dvh
      flex
      flex-col
      items-center
      justify-center
      gap-10
      md:grid
      md:grid-flow-col
    "
  >
    <Container
      class="
        flex
        items-center
      "
    >
      <h1
        class="
          text-5xl
          font-black
          text-center
          md:text-left
      "
    >
        <span>
          Let me turn your<br>ideas into
        </span>
        <span
          class="
            bg-gradient-to-r
            from-blue-400
            to-pink-400
            text-transparent
            bg-clip-text
          "
        >
          reality
        </span>
      </h1>
    </Container>
    <Container
      class="
        flex
        items-center
      "
    >
      <p
        class="
          max-w-lg
          text-slate-300
          text-center
          md:text-left
        "
      >
        Hello! My name is kyomi. I am a Brazilian full-stack developer studying
        software engineering at the University of Brasília.
      </p>
    </Container>
  </Container>
</template>
