<template>
  <div
    class="
      flex
      flex-col
      items-center
      justify-center
      gap-4
    "
  >
    <NuxtImg
      src="/github/bitterteriyaki.png"
      class="rounded-full"
      sizes="128px sm:160px md:208px"
      alt="kyomi's avatar on GitHub"
      placeholder
    />
    <h1
      class="
        text-4xl
        font-black
      "
    >
      <span>
        Let me turn your<br>ideas into
      </span>
      <span
        class="
          bg-gradient-to-r
          from-blue-500
          to-pink-400
          text-transparent
          bg-clip-text
        "
      >
        reality
      </span>
    </h1>
  </div>
</template>
